repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/zricethezav/gitleaks
    rev: v8.16.1
    hooks:
    -   id: gitleaks

# -   repo: https://github.com/mxab/pre-commit-trivy.git
#     rev: v0.3.0
#     hooks:
#     -   id: trivyfs-docker
#         args:
#           - --skip-dirs
#           - ./tests
#           - --security-checks
#           - vuln
#           - . # last arg indicates the path/file to scan
